apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-cluster-test
rules:
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-cluster-test-binding
subjects:
  - kind: User
    name: "<my-email>" # Replace with your email
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: chaos-mesh-cluster-test
  apiGroup: rbac.authorization.k8s.io
