clusterOperator:
  nodeSelector:
    node-role: worker
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: NotIn
                values:
                  - us
msgToplogyOperator:
  nodeSelector:
    node-role: worker
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: NotIn
                values:
                  - us
