rabbitmqImage:
  repository: bitnamilegacy/rabbitmq
credentialUpdaterImage:
  repository: bitnamilegacy/rmq-default-credential-updater
clusterOperator:
  replicaCount: 4
  image:
    repository: bitnamilegacy/rabbitmq-cluster-operator
  nodeSelector:
    node-role: web
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - rabbitmq-operator
          topologyKey: "kubernetes.io/hostname"
msgTopologyOperator:
  replicaCount: 4
  image:
    repository: bitnamilegacy/rmq-messaging-topology-operator
  nodeSelector:
    node-role: web
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - messaging-topology-operator
          topologyKey: "kubernetes.io/hostname"
